version: '3.4'
 
services:
    db:
     image: mysql:8.0
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: graphdb
       MYSQL_USER: chart
       MYSQL_PASSWORD: chart
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
    2dchart:
     image: image2dchart:dev
     build:
       context: .
     ports:
       - "5000:80"
     depends_on:
      - db
volumes:
    dbdata: